version: 0.0
os: linux
files:
  - source: index.html
    destination: /opt/temp-deploy/  
    overwrite: true

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
